// Package test checks that the code generated by bpf2go conforms to a
// specific API.
package test

// $BPF_CLANG, $BPF_STRIP and $BPF_CFLAGS are set by the Makefile.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc $BPF_CLANG -strip $BPF_STRIP test ../testdata/minimal.c
