---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    allow:
      # Only manage direct dependencies in Pipfile, ignore transient
      # dependencies only appearing in Pipfile.lock.
      - dependency-name: "*"
        dependency-type: "direct"
