---
issues:
  exclude-rules:
    # syscall param structs will have unused fields in Go code.
    - path: syscall.*.go
      linters:
        - structcheck

linters:
  enable:
    - misspell
    - deadcode
    - gosimple
    - goimports

    # Could be enabled later:
    # - gocyclo
    # - prealloc
    # - maligned
    # - gosec
