---
issues:
  exclude-rules:
    # syscall param structs will have unused fields in Go code.
    - path: syscall.*.go
      linters:
        - structcheck

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - gofmt
