---
issues:
  exclude-rules:
    # syscall param structs will have unused fields in Go code.
    - path: syscall.*.go
      linters:
        - structcheck

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

    # Could be enabled later:
    # - gocyclo
    # - prealloc
    # - maligned

linters-settings:
  gosec:
    excludes:
      - G204
      - G401
      - G404
    config:
      G306: "0660"
