---
issues:
  exclude-rules:
    # syscall param structs will have unused fields in Go code.
    - path: syscall.*.go
      linters:
        - structcheck

linters:
  disable-all: true
  enable:
    - errcheck
    - gci
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

    # Could be enabled later:
    # - gocyclo
    # - maligned
    # - gosec

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cilium)
