// Code generated by "stringer -type LogLevel -trimprefix Log"; DO NOT EDIT.

package ebpf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevelBranch-1]
	_ = x[LogLevelInstruction-2]
	_ = x[LogLevelStats-4]
}

const (
	_LogLevel_name_0 = "LevelBranchLevelInstruction"
	_LogLevel_name_1 = "LevelStats"
)

var (
	_LogLevel_index_0 = [...]uint8{0, 11, 27}
)

func (i LogLevel) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _LogLevel_name_0[_LogLevel_index_0[i]:_LogLevel_index_0[i+1]]
	case i == 4:
		return _LogLevel_name_1
	default:
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
