// Code generated by "stringer -type ProgramType -output types_program_string_windows.go -tags windows"; DO NOT EDIT.

package ebpf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedProgram-0]
	_ = x[XDP-1]
	_ = x[CGroupSockAddr-2]
	_ = x[SockOps-3]
	_ = x[WinXDPTest-998]
	_ = x[WinSample-999]
	_ = x[SocketFilter-1000000]
	_ = x[Kprobe-1000001]
	_ = x[SchedCLS-1000002]
	_ = x[SchedACT-1000003]
	_ = x[TracePoint-1000004]
	_ = x[PerfEvent-1000005]
	_ = x[CGroupSKB-1000006]
	_ = x[CGroupSock-1000007]
	_ = x[LWTIn-1000008]
	_ = x[LWTOut-1000009]
	_ = x[LWTXmit-1000010]
	_ = x[SkSKB-1000011]
	_ = x[CGroupDevice-1000012]
	_ = x[SkMsg-1000013]
	_ = x[RawTracepoint-1000014]
	_ = x[LWTSeg6Local-1000015]
	_ = x[LircMode2-1000016]
	_ = x[SkReuseport-1000017]
	_ = x[FlowDissector-1000018]
	_ = x[CGroupSysctl-1000019]
	_ = x[RawTracepointWritable-1000020]
	_ = x[CGroupSockopt-1000021]
	_ = x[Tracing-1000022]
	_ = x[StructOps-1000023]
	_ = x[Extension-1000024]
	_ = x[LSM-1000025]
	_ = x[SkLookup-1000026]
	_ = x[Syscall-1000027]
	_ = x[Netfilter-1000028]
}

const (
	_ProgramType_name_0 = "UnspecifiedProgramXDPCGroupSockAddrSockOps"
	_ProgramType_name_1 = "WinXDPTestWinSample"
	_ProgramType_name_2 = "SocketFilterKprobeSchedCLSSchedACTTracePointPerfEventCGroupSKBCGroupSockLWTInLWTOutLWTXmitSkSKBCGroupDeviceSkMsgRawTracepointLWTSeg6LocalLircMode2SkReuseportFlowDissectorCGroupSysctlRawTracepointWritableCGroupSockoptTracingStructOpsExtensionLSMSkLookupSyscallNetfilter"
)

var (
	_ProgramType_index_0 = [...]uint8{0, 18, 21, 35, 42}
	_ProgramType_index_1 = [...]uint8{0, 10, 19}
	_ProgramType_index_2 = [...]uint16{0, 12, 18, 26, 34, 44, 53, 62, 72, 77, 83, 90, 95, 107, 112, 125, 137, 146, 157, 170, 182, 203, 216, 223, 232, 241, 244, 252, 259, 268}
)

func (i ProgramType) String() string {
	switch {
	case i <= 3:
		return _ProgramType_name_0[_ProgramType_index_0[i]:_ProgramType_index_0[i+1]]
	case 998 <= i && i <= 999:
		i -= 998
		return _ProgramType_name_1[_ProgramType_index_1[i]:_ProgramType_index_1[i+1]]
	case 1000000 <= i && i <= 1000028:
		i -= 1000000
		return _ProgramType_name_2[_ProgramType_index_2[i]:_ProgramType_index_2[i+1]]
	default:
		return "ProgramType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
