// Code generated by "stringer -output types_string.go -type=MapType,ProgType"; DO NOT EDIT.

package ebpf

import "strconv"

const _MapType_name = "UnspecifiedMapHashArrayProgramArrayPerfEventArrayPerCPUHashPerCPUArrayStackTraceCGroupArrayLRUHashLRUCPUHashLPMTrieArrayOfMapsHashOfMaps"

var _MapType_index = [...]uint8{0, 14, 18, 23, 35, 49, 59, 70, 80, 91, 98, 108, 115, 126, 136}

func (i MapType) String() string {
	if i >= MapType(len(_MapType_index)-1) {
		return "MapType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MapType_name[_MapType_index[i]:_MapType_index[i+1]]
}

const _ProgType_name = "UnrecognizedSocketFilterKprobeSchedCLSSchedACTTracePointXDPPerfEventCGroupSKBCGroupSockLWTInLWTOutLWTXmitSockOps"

var _ProgType_index = [...]uint8{0, 12, 24, 30, 38, 46, 56, 59, 68, 77, 87, 92, 98, 105, 112}

func (i ProgType) String() string {
	if i >= ProgType(len(_ProgType_index)-1) {
		return "ProgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProgType_name[_ProgType_index[i]:_ProgType_index[i+1]]
}
