// Code generated by "stringer -output types_string.go -type=MapType,ProgType"; DO NOT EDIT.

package ebpf

import "strconv"

const _MapType_name = "HashArrayProgramArrayPerfEventArrayPerCPUHashPerCPUArrayStackTraceCGroupArrayLRUHashLRUCPUHashLPMTrieArrayOfMapsHashOfMaps"

var _MapType_index = [...]uint8{0, 4, 9, 21, 35, 45, 56, 66, 77, 84, 94, 101, 112, 122}

func (i MapType) String() string {
	i -= 1
	if i >= MapType(len(_MapType_index)-1) {
		return "MapType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MapType_name[_MapType_index[i]:_MapType_index[i+1]]
}

const _ProgType_name = "UnrecognizedSocketFilterKprobeSchedCLSSchedACTTracePointXDPPerfEventCGroupSKBCGroupSockLWTInLWTOutLWTXmitSockOps"

var _ProgType_index = [...]uint8{0, 12, 24, 30, 38, 46, 56, 59, 68, 77, 87, 92, 98, 105, 112}

func (i ProgType) String() string {
	if i >= ProgType(len(_ProgType_index)-1) {
		return "ProgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProgType_name[_ProgType_index[i]:_ProgType_index[i+1]]
}
