// Code generated by "stringer -type AttachType -trimprefix Attach -output types_attach_string_windows.go -tags windows"; DO NOT EDIT.

package ebpf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttachNone-0]
	_ = x[AttachXDP-1]
	_ = x[AttachBind-2]
	_ = x[AttachCGroupInet4Connect-3]
	_ = x[AttachCGroupInet6Connect-4]
	_ = x[AttachCgroupInet4RecvAccept-5]
	_ = x[AttachCgroupInet6RecvAccept-6]
	_ = x[AttachCGroupSockOps-7]
	_ = x[AttachSample-8]
	_ = x[AttachXDPTest-9]
	_ = x[AttachCGroupInetIngress-1000000]
	_ = x[AttachCGroupInetEgress-1000001]
	_ = x[AttachCGroupInetSockCreate-1000002]
	_ = x[AttachSkSKBStreamParser-1000003]
	_ = x[AttachSkSKBStreamVerdict-1000004]
	_ = x[AttachCGroupDevice-1000005]
	_ = x[AttachSkMsgVerdict-1000006]
	_ = x[AttachCGroupInet4Bind-1000007]
	_ = x[AttachCGroupInet6Bind-1000008]
	_ = x[AttachCGroupInet4PostBind-1000009]
	_ = x[AttachCGroupInet6PostBind-1000010]
	_ = x[AttachCGroupUDP4Sendmsg-1000011]
	_ = x[AttachCGroupUDP6Sendmsg-1000012]
	_ = x[AttachLircMode2-1000013]
	_ = x[AttachFlowDissector-1000014]
	_ = x[AttachCGroupSysctl-1000015]
	_ = x[AttachCGroupUDP4Recvmsg-1000016]
	_ = x[AttachCGroupUDP6Recvmsg-1000017]
	_ = x[AttachCGroupGetsockopt-1000018]
	_ = x[AttachCGroupSetsockopt-1000019]
	_ = x[AttachTraceRawTp-1000020]
	_ = x[AttachTraceFEntry-1000021]
	_ = x[AttachTraceFExit-1000022]
	_ = x[AttachModifyReturn-1000023]
	_ = x[AttachLSMMac-1000024]
	_ = x[AttachTraceIter-1000025]
	_ = x[AttachCgroupInet4GetPeername-1000026]
	_ = x[AttachCgroupInet6GetPeername-1000027]
	_ = x[AttachCgroupInet4GetSockname-1000028]
	_ = x[AttachCgroupInet6GetSockname-1000029]
	_ = x[AttachXDPDevMap-1000030]
	_ = x[AttachCgroupInetSockRelease-1000031]
	_ = x[AttachXDPCPUMap-1000032]
	_ = x[AttachSkLookup-1000033]
	_ = x[AttachSkSKBVerdict-1000034]
	_ = x[AttachSkReuseportSelect-1000035]
	_ = x[AttachSkReuseportSelectOrMigrate-1000036]
	_ = x[AttachPerfEvent-1000037]
	_ = x[AttachTraceKprobeMulti-1000038]
	_ = x[AttachLSMCgroup-1000039]
	_ = x[AttachStructOps-1000040]
	_ = x[AttachNetfilter-1000041]
	_ = x[AttachTCXIngress-1000042]
	_ = x[AttachTCXEgress-1000043]
	_ = x[AttachTraceUprobeMulti-1000044]
	_ = x[AttachCgroupUnixConnect-1000045]
	_ = x[AttachCgroupUnixSendmsg-1000046]
	_ = x[AttachCgroupUnixRecvmsg-1000047]
	_ = x[AttachCgroupUnixGetpeername-1000048]
	_ = x[AttachCgroupUnixGetsockname-1000049]
	_ = x[AttachNetkitPrimary-1000050]
	_ = x[AttachNetkitPeer-1000051]
}

const (
	_AttachType_name_0 = "NoneXDPBindCGroupInet4ConnectCGroupInet6ConnectCgroupInet4RecvAcceptCgroupInet6RecvAcceptCGroupSockOpsSampleXDPTest"
	_AttachType_name_1 = "CGroupInetIngressCGroupInetEgressCGroupInetSockCreateSkSKBStreamParserSkSKBStreamVerdictCGroupDeviceSkMsgVerdictCGroupInet4BindCGroupInet6BindCGroupInet4PostBindCGroupInet6PostBindCGroupUDP4SendmsgCGroupUDP6SendmsgLircMode2FlowDissectorCGroupSysctlCGroupUDP4RecvmsgCGroupUDP6RecvmsgCGroupGetsockoptCGroupSetsockoptTraceRawTpTraceFEntryTraceFExitModifyReturnLSMMacTraceIterCgroupInet4GetPeernameCgroupInet6GetPeernameCgroupInet4GetSocknameCgroupInet6GetSocknameXDPDevMapCgroupInetSockReleaseXDPCPUMapSkLookupSkSKBVerdictSkReuseportSelectSkReuseportSelectOrMigratePerfEventTraceKprobeMultiLSMCgroupStructOpsNetfilterTCXIngressTCXEgressTraceUprobeMultiCgroupUnixConnectCgroupUnixSendmsgCgroupUnixRecvmsgCgroupUnixGetpeernameCgroupUnixGetsocknameNetkitPrimaryNetkitPeer"
)

var (
	_AttachType_index_0 = [...]uint8{0, 4, 7, 11, 29, 47, 68, 89, 102, 108, 115}
	_AttachType_index_1 = [...]uint16{0, 17, 33, 53, 70, 88, 100, 112, 127, 142, 161, 180, 197, 214, 223, 236, 248, 265, 282, 298, 314, 324, 335, 345, 357, 363, 372, 394, 416, 438, 460, 469, 490, 499, 507, 519, 536, 562, 571, 587, 596, 605, 614, 624, 633, 649, 666, 683, 700, 721, 742, 755, 765}
)

func (i AttachType) String() string {
	switch {
	case i <= 9:
		return _AttachType_name_0[_AttachType_index_0[i]:_AttachType_index_0[i+1]]
	case 1000000 <= i && i <= 1000051:
		i -= 1000000
		return _AttachType_name_1[_AttachType_index_1[i]:_AttachType_index_1[i+1]]
	default:
		return "AttachType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
