// Code generated by "stringer -type=MapType,PinType -output types_string_windows.go -tags windows"; DO NOT EDIT.

package ebpf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedMap-0]
	_ = x[Hash-1]
	_ = x[Array-2]
	_ = x[ProgramArray-3]
	_ = x[PerCPUHash-4]
	_ = x[PerCPUArray-5]
	_ = x[HashOfMaps-6]
	_ = x[ArrayOfMaps-7]
	_ = x[LRUHash-8]
	_ = x[LPMTrie-9]
	_ = x[Queue-10]
	_ = x[LRUCPUHash-11]
	_ = x[Stack-12]
	_ = x[RingBuf-13]
	_ = x[PerfEventArray-1000000]
	_ = x[StackTrace-1000001]
	_ = x[CGroupArray-1000002]
	_ = x[DevMap-1000003]
	_ = x[SockMap-1000004]
	_ = x[CPUMap-1000005]
	_ = x[XSKMap-1000006]
	_ = x[SockHash-1000007]
	_ = x[CGroupStorage-1000008]
	_ = x[ReusePortSockArray-1000009]
	_ = x[PerCPUCGroupStorage-1000010]
	_ = x[SkStorage-1000011]
	_ = x[DevMapHash-1000012]
	_ = x[StructOpsMap-1000013]
	_ = x[InodeStorage-1000014]
	_ = x[TaskStorage-1000015]
}

const (
	_MapType_name_0 = "UnspecifiedMapHashArrayProgramArrayPerCPUHashPerCPUArrayHashOfMapsArrayOfMapsLRUHashLPMTrieQueueLRUCPUHashStackRingBuf"
	_MapType_name_1 = "PerfEventArrayStackTraceCGroupArrayDevMapSockMapCPUMapXSKMapSockHashCGroupStorageReusePortSockArrayPerCPUCGroupStorageSkStorageDevMapHashStructOpsMapInodeStorageTaskStorage"
)

var (
	_MapType_index_0 = [...]uint8{0, 14, 18, 23, 35, 45, 56, 66, 77, 84, 91, 96, 106, 111, 118}
	_MapType_index_1 = [...]uint8{0, 14, 24, 35, 41, 48, 54, 60, 68, 81, 99, 118, 127, 137, 149, 161, 172}
)

func (i MapType) String() string {
	switch {
	case i <= 13:
		return _MapType_name_0[_MapType_index_0[i]:_MapType_index_0[i+1]]
	case 1000000 <= i && i <= 1000015:
		i -= 1000000
		return _MapType_name_1[_MapType_index_1[i]:_MapType_index_1[i+1]]
	default:
		return "MapType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PinNone-0]
	_ = x[PinByName-1]
}

const _PinType_name = "PinNonePinByName"

var _PinType_index = [...]uint8{0, 7, 16}

func (i PinType) String() string {
	if i >= PinType(len(_PinType_index)-1) {
		return "PinType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PinType_name[_PinType_index[i]:_PinType_index[i+1]]
}
