// Code generated by "stringer -output types_string.go -type=MapType,ProgType,Func"; DO NOT EDIT.

package ebpf

import "strconv"

const _MapType_name = "HashArrayProgramArrayPerfEventArrayPerCPUHashPerCPUArrayStackTraceCGroupArrayLRUHashLRUCPUHashLPMTrieArrayOfMapsHashOfMaps"

var _MapType_index = [...]uint8{0, 4, 9, 21, 35, 45, 56, 66, 77, 84, 94, 101, 112, 122}

func (i MapType) String() string {
	i -= 1
	if i >= MapType(len(_MapType_index)-1) {
		return "MapType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MapType_name[_MapType_index[i]:_MapType_index[i+1]]
}

const _ProgType_name = "UnrecognizedSocketFilterKprobeSchedCLSSchedACTTracePointXDPPerfEventCGroupSKBCGroupSockLWTInLWTOutLWTXmitSockOps"

var _ProgType_index = [...]uint8{0, 12, 24, 30, 38, 46, 56, 59, 68, 77, 87, 92, 98, 105, 112}

func (i ProgType) String() string {
	if i >= ProgType(len(_ProgType_index)-1) {
		return "ProgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProgType_name[_ProgType_index[i]:_ProgType_index[i+1]]
}

const _Func_name = "MapLookupElementMapUpdateElementMapDeleteElementProbeReadKtimeGetNSTracePrintkGetPRandomu32GetSMPProcessorIDSKBStoreBytesCSUMReplaceL3CSUMReplaceL4TailCallCloneRedirectGetCurrentPIDTGIDGetCurrentUIDGIDGetCurrentCommGetCGroupClassIDSKBVlanPushSKBVlanPopSKBGetTunnelKeySKBSetTunnelKeyPerfEventReadRedirectGetRouteRealmPerfEventOutputGetStackIDCsumDiffSKBGetTunnelOptSKBSetTunnelOptSKBChangeProtoSKBChangeTypeSKBUnderCGroupGetHashRecalcGetCurrentTaskProbeWriteUserCurrentTaskUnderCGroupSKBChangeTailSKBPullDataCSUMUpdateSetHashInvalidGetNUMANodeIDSKBChangeHeadXDPAdjustHeadProbeReadStrGetSocketCookieGetSocketUIDSetHashSetSockOptSKBAdjustRoom"

var _Func_index = [...]uint16{0, 16, 32, 48, 57, 67, 78, 91, 108, 121, 134, 147, 155, 168, 185, 201, 215, 231, 242, 252, 267, 282, 295, 303, 316, 331, 341, 349, 364, 379, 393, 406, 420, 433, 447, 461, 483, 496, 507, 517, 531, 544, 557, 570, 582, 597, 609, 616, 626, 639}

func (i Func) String() string {
	i -= 1
	if i < 0 || i >= Func(len(_Func_index)-1) {
		return "Func(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Func_name[_Func_index[i]:_Func_index[i+1]]
}
