// Code generated by internal/cmd/genwinfunctions.awk; DO NOT EDIT.

package asm

// Code in this file is derived from eBPF for Windows, available under the MIT License.

import "github.com/cilium/ebpf/internal"

// Built-in functions (Windows).
const (
	WindowsFnMapLookupElem          = BuiltinFunc(internal.WindowsTag | 1)
	WindowsFnMapUpdateElem          = BuiltinFunc(internal.WindowsTag | 2)
	WindowsFnMapDeleteElem          = BuiltinFunc(internal.WindowsTag | 3)
	WindowsFnMapLookupAndDeleteElem = BuiltinFunc(internal.WindowsTag | 4)
	WindowsFnTailCall               = BuiltinFunc(internal.WindowsTag | 5)
	WindowsFnGetPrandomU32          = BuiltinFunc(internal.WindowsTag | 6)
	WindowsFnKtimeGetBootNs         = BuiltinFunc(internal.WindowsTag | 7)
	WindowsFnGetSmpProcessorId      = BuiltinFunc(internal.WindowsTag | 8)
	WindowsFnKtimeGetNs             = BuiltinFunc(internal.WindowsTag | 9)
	WindowsFnCsumDiff               = BuiltinFunc(internal.WindowsTag | 10)
	WindowsFnRingbufOutput          = BuiltinFunc(internal.WindowsTag | 11)
	WindowsFnTracePrintk2           = BuiltinFunc(internal.WindowsTag | 12)
	WindowsFnTracePrintk3           = BuiltinFunc(internal.WindowsTag | 13)
	WindowsFnTracePrintk4           = BuiltinFunc(internal.WindowsTag | 14)
	WindowsFnTracePrintk5           = BuiltinFunc(internal.WindowsTag | 15)
	WindowsFnMapPushElem            = BuiltinFunc(internal.WindowsTag | 16)
	WindowsFnMapPopElem             = BuiltinFunc(internal.WindowsTag | 17)
	WindowsFnMapPeekElem            = BuiltinFunc(internal.WindowsTag | 18)
	WindowsFnGetCurrentPidTgid      = BuiltinFunc(internal.WindowsTag | 19)
	WindowsFnGetCurrentLogonId      = BuiltinFunc(internal.WindowsTag | 20)
	WindowsFnIsCurrentAdmin         = BuiltinFunc(internal.WindowsTag | 21)
	WindowsFnMemcpy                 = BuiltinFunc(internal.WindowsTag | 22)
	WindowsFnMemcmp                 = BuiltinFunc(internal.WindowsTag | 23)
	WindowsFnMemset                 = BuiltinFunc(internal.WindowsTag | 24)
	WindowsFnMemmove                = BuiltinFunc(internal.WindowsTag | 25)
	WindowsFnGetSocketCookie        = BuiltinFunc(internal.WindowsTag | 26)
	WindowsFnStrncpyS               = BuiltinFunc(internal.WindowsTag | 27)
	WindowsFnStrncatS               = BuiltinFunc(internal.WindowsTag | 28)
	WindowsFnStrnlenS               = BuiltinFunc(internal.WindowsTag | 29)
	WindowsFnKtimeGetBootMs         = BuiltinFunc(internal.WindowsTag | 30)
	WindowsFnKtimeGetMs             = BuiltinFunc(internal.WindowsTag | 31)
)
