// Code generated by "stringer -output func_string.go -type=BuiltinFunc"; DO NOT EDIT.

package asm

import "strconv"

const _BuiltinFunc_name = "MapLookupElementMapUpdateElementMapDeleteElementProbeReadKtimeGetNSTracePrintkGetPRandomu32GetSMPProcessorIDSKBStoreBytesCSUMReplaceL3CSUMReplaceL4TailCallCloneRedirectGetCurrentPIDTGIDGetCurrentUIDGIDGetCurrentCommGetCGroupClassIDSKBVlanPushSKBVlanPopSKBGetTunnelKeySKBSetTunnelKeyPerfEventReadRedirectGetRouteRealmPerfEventOutputGetStackIDCsumDiffSKBGetTunnelOptSKBSetTunnelOptSKBChangeProtoSKBChangeTypeSKBUnderCGroupGetHashRecalcGetCurrentTaskProbeWriteUserCurrentTaskUnderCGroupSKBChangeTailSKBPullDataCSUMUpdateSetHashInvalidGetNUMANodeIDSKBChangeHeadXDPAdjustHeadProbeReadStrGetSocketCookieGetSocketUIDSetHashSetSockOptSKBAdjustRoom"

var _BuiltinFunc_index = [...]uint16{0, 16, 32, 48, 57, 67, 78, 91, 108, 121, 134, 147, 155, 168, 185, 201, 215, 231, 242, 252, 267, 282, 295, 303, 316, 331, 341, 349, 364, 379, 393, 406, 420, 433, 447, 461, 483, 496, 507, 517, 531, 544, 557, 570, 582, 597, 609, 616, 626, 639}

func (i BuiltinFunc) String() string {
	i -= 1
	if i < 0 || i >= BuiltinFunc(len(_BuiltinFunc_index)-1) {
		return "BuiltinFunc(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BuiltinFunc_name[_BuiltinFunc_index[i]:_BuiltinFunc_index[i+1]]
}
