// Code generated by "stringer -output jump_string.go -type=JumpOp"; DO NOT EDIT.

package asm

import "strconv"

const _JumpOp_name = "JaJEqJGTJGEJSEJNEJSGTJSGECallExitInvalidJumpOp"

var _JumpOp_map = map[JumpOp]string{
	0:   _JumpOp_name[0:2],
	16:  _JumpOp_name[2:5],
	32:  _JumpOp_name[5:8],
	48:  _JumpOp_name[8:11],
	64:  _JumpOp_name[11:14],
	80:  _JumpOp_name[14:17],
	96:  _JumpOp_name[17:21],
	112: _JumpOp_name[21:25],
	128: _JumpOp_name[25:29],
	144: _JumpOp_name[29:33],
	255: _JumpOp_name[33:46],
}

func (i JumpOp) String() string {
	if str, ok := _JumpOp_map[i]; ok {
		return str
	}
	return "JumpOp(" + strconv.FormatInt(int64(i), 10) + ")"
}
