// Code generated by "stringer -output load_store_string.go -type=Mode,Size,Atomic"; DO NOT EDIT.

package asm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidMode-255]
	_ = x[ImmMode-0]
	_ = x[AbsMode-32]
	_ = x[IndMode-64]
	_ = x[MemMode-96]
	_ = x[MemSXMode-128]
	_ = x[AtomicMode-192]
}

const (
	_Mode_name_0 = "ImmMode"
	_Mode_name_1 = "AbsMode"
	_Mode_name_2 = "IndMode"
	_Mode_name_3 = "MemMode"
	_Mode_name_4 = "MemSXMode"
	_Mode_name_5 = "AtomicMode"
	_Mode_name_6 = "InvalidMode"
)

func (i Mode) String() string {
	switch {
	case i == 0:
		return _Mode_name_0
	case i == 32:
		return _Mode_name_1
	case i == 64:
		return _Mode_name_2
	case i == 96:
		return _Mode_name_3
	case i == 128:
		return _Mode_name_4
	case i == 192:
		return _Mode_name_5
	case i == 255:
		return _Mode_name_6
	default:
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidSize-255]
	_ = x[DWord-24]
	_ = x[Word-0]
	_ = x[Half-8]
	_ = x[Byte-16]
}

const (
	_Size_name_0 = "Word"
	_Size_name_1 = "Half"
	_Size_name_2 = "Byte"
	_Size_name_3 = "DWord"
	_Size_name_4 = "InvalidSize"
)

func (i Size) String() string {
	switch {
	case i == 0:
		return _Size_name_0
	case i == 8:
		return _Size_name_1
	case i == 16:
		return _Size_name_2
	case i == 24:
		return _Size_name_3
	case i == 255:
		return _Size_name_4
	default:
		return "Size(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidAtomic-4294967295]
	_ = x[AddAtomic-0]
	_ = x[FetchAddAtomic-65536]
	_ = x[AndAtomic-5242880]
	_ = x[FetchAndAtomic-5308416]
	_ = x[OrAtomic-4194304]
	_ = x[FetchOrAtomic-4259840]
	_ = x[XorAtomic-10485760]
	_ = x[FetchXorAtomic-10551296]
	_ = x[Fetch-65536]
	_ = x[XchgAtomic-14745600]
	_ = x[CmpXchgAtomic-15794176]
	_ = x[LdAcqAtomic-16777216]
	_ = x[StRelAtomic-17825792]
}

const _Atomic_name = "AddAtomicFetchAddAtomicOrAtomicFetchOrAtomicAndAtomicFetchAndAtomicXorAtomicFetchXorAtomicXchgAtomicCmpXchgAtomicLdAcqAtomicStRelAtomicInvalidAtomic"

var _Atomic_map = map[Atomic]string{
	0:          _Atomic_name[0:9],
	65536:      _Atomic_name[9:23],
	4194304:    _Atomic_name[23:31],
	4259840:    _Atomic_name[31:44],
	5242880:    _Atomic_name[44:53],
	5308416:    _Atomic_name[53:67],
	10485760:   _Atomic_name[67:76],
	10551296:   _Atomic_name[76:90],
	14745600:   _Atomic_name[90:100],
	15794176:   _Atomic_name[100:113],
	16777216:   _Atomic_name[113:124],
	17825792:   _Atomic_name[124:135],
	4294967295: _Atomic_name[135:148],
}

func (i Atomic) String() string {
	if str, ok := _Atomic_map[i]; ok {
		return str
	}
	return "Atomic(" + strconv.FormatInt(int64(i), 10) + ")"
}
