contact_links:
  - name: Questions
    url: https://github.com/cilium/ebpf/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Slack
    url: https://cilium.slack.com/messages/ebpf-go
    about: Join our slack.
