// Code generated by "stringer -output macros_string.go -type=MacroType"; DO NOT EDIT.

package features

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LargeInsn-0]
	_ = x[BoundedLoops-1]
	_ = x[V2ISA-2]
	_ = x[V3ISA-3]
	_ = x[maxMacroType-4]
}

const _MacroType_name = "LargeInsnBoundedLoopsV2ISAV3ISAmaxMacroType"

var _MacroType_index = [...]uint8{0, 9, 21, 26, 31, 43}

func (i MacroType) String() string {
	if i >= MacroType(len(_MacroType_index)-1) {
		return "MacroType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MacroType_name[_MacroType_index[i]:_MacroType_index[i+1]]
}
