// Code generated by "stringer -type MapFlags"; DO NOT EDIT.

package sys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BPF_F_NO_PREALLOC-1]
	_ = x[BPF_F_RDONLY_PROG-128]
	_ = x[BPF_F_WRONLY_PROG-256]
	_ = x[BPF_F_MMAPABLE-1024]
	_ = x[BPF_F_INNER_MAP-4096]
}

const (
	_MapFlags_name_0 = "BPF_F_NO_PREALLOC"
	_MapFlags_name_1 = "BPF_F_RDONLY_PROG"
	_MapFlags_name_2 = "BPF_F_WRONLY_PROG"
	_MapFlags_name_3 = "BPF_F_MMAPABLE"
	_MapFlags_name_4 = "BPF_F_INNER_MAP"
)

func (i MapFlags) String() string {
	switch {
	case i == 1:
		return _MapFlags_name_0
	case i == 128:
		return _MapFlags_name_1
	case i == 256:
		return _MapFlags_name_2
	case i == 1024:
		return _MapFlags_name_3
	case i == 4096:
		return _MapFlags_name_4
	default:
		return "MapFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
