// Code generated by "stringer -type=Platform"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedPlatform-0]
	_ = x[Linux-1]
	_ = x[Windows-2]
}

const _Platform_name = "UnspecifiedPlatformLinuxWindows"

var _Platform_index = [...]uint8{0, 19, 24, 31}

func (i Platform) String() string {
	if i < 0 || i >= Platform(len(_Platform_index)-1) {
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Platform_name[_Platform_index[i]:_Platform_index[i+1]]
}
