on:
  pull_request:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.1'
      - name: Run ORT
        uses: edulix/ort-action@v0.1.2
